### ISSUE TITLE
Breaking Changes for "0.15.0"

### ISSUE THREAD

**Issue by minghuaw** [minghuaw/azeventhubs#14]
- [x] minghuaw/azure-sdk-for-rust#21
- [x] minghuaw/azure-sdk-for-rust#20
- [x] minghuaw/azure-sdk-for-rust#25
